

all:
	@echo "Not implemented"; exit 1

build-polygon:
	javac -d cls src/PolygonExample.java

run-polygon:
	@echo "Running Polygon Example"
	@java -cp cls Shape2D
	@echo "Test Complete"

build-integertree:
	javac -d cls src/IntegerTree.java

run-integertree:
	java -cp cls IntegerTree

build-minstack:
	javac -d cls src/Stack.java src/SimpleLinkedStack.java src/MinStack.java

run-minstack:
	java -cp cls MinStack
